version: "3.4"
services:

  k6:
    build:
      context: .
      dockerfile: load/k6/Dockerfile
    image: performance-testing/k6:latest
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - TARGET_URL=${TARGET_URL:-https://comunidadedoamor.site}
      - MAX_VUS=${MAX_VUS:-200}
      - TEST_DURATION=${TEST_DURATION:-30m}
      - RAMP_UP=${RAMP_UP:-2m}
      - RAMP_DOWN=${RAMP_DOWN:-1m}
    depends_on:
      - influxdb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  influxdb:
    image: influxdb:1.8
    ports:
      - "${INFLUXDB_PORT:-7429}:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "${GRAFANA_PORT:-4821}:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      - influxdb
    volumes:
      - ./load/grafana:/etc/grafana/provisioning/
